export const domains = [
  {
    num: "01",
    title: "Accidents de la circulation",
    subtitle: "Loi n° 85-677 du 5 juillet 1985 dite loi Badinter",
    tagline: "Victimes conductrices, passagères, piétons ou cyclistes.",
    body: "Tout accident impliquant un véhicule terrestre à moteur ouvre droit à indemnisation au bénéfice des victimes, qu'elles soient conductrices, passagères, piétons ou cyclistes. La loi Badinter du 5 juillet 1985 organise un régime spécifique d'indemnisation, distinct du droit commun de la responsabilité civile.\n\nLes victimes non conductrices bénéficient d'un régime d'indemnisation particulièrement protecteur : leur droit à réparation ne peut être réduit que dans des cas très limités. Les victimes conductrices sont indemnisées en fonction de leur éventuelle faute dans la survenance de l'accident.",
    procedure: "La procédure implique la négociation d'une offre d'indemnisation avec l'assureur du responsable, ou, à défaut d'assureur identifiable, la saisine du Fonds de Garantie des Assurances Obligatoires (FGAO) — notamment en cas d'auteur inconnu ou de véhicule non assuré. En cas d'offre insuffisante, la voie contentieuse devant le tribunal judiciaire est ouverte.",
  },
  {
    num: "02",
    title: "Accidents médicaux",
    subtitle: "Loi n° 2002-303 du 4 mars 2002 dite loi Kouchner",
    tagline: "Erreurs de diagnostic, défauts de soin, infections nosocomiales, aléas thérapeutiques.",
    body: "La responsabilité médicale peut résulter d'une faute du professionnel de santé, d'une erreur de diagnostic, d'un défaut de soin, d'un manquement à l'obligation d'information, ou d'un accident médical non fautif relevant du régime de l'aléa thérapeutique.\n\nLes infections nosocomiales engagent la responsabilité de l'établissement de soins dès lors qu'elles sont acquises lors d'une prise en charge médicale. Les actes pratiqués en secteur public relèvent de la responsabilité administrative ; ceux pratiqués en secteur privé relèvent de la responsabilité civile.",
    procedure: "Deux voies sont ouvertes : la procédure amiable devant la Commission de Conciliation et d'Indemnisation (CCI), qui peut aboutir à une offre de l'ONIAM ou de l'assureur du professionnel, ou la voie contentieuse devant le tribunal judiciaire (secteur privé) ou le tribunal administratif (secteur public). Ces deux voies ne sont pas exclusives l'une de l'autre.",
  },
  {
    num: "03",
    title: "Accidents de la vie",
    subtitle: "Droit commun de la responsabilité · droit des assurances",
    tagline: "Accidents domestiques, de sport, de loisirs.",
    body: "Les accidents survenus dans la sphère privée — au domicile, lors de la pratique sportive ou d'activités de loisirs — peuvent ouvrir droit à indemnisation sur deux fondements distincts : la mise en jeu de la responsabilité civile d'un tiers fautif, et/ou l'activation des garanties contractuelles souscrites.\n\nLa Garantie des Accidents de la Vie (GAV) est un contrat d'assurance individuelle qui indemnise la victime quelles que soient les circonstances, sans avoir à démontrer la faute d'un tiers. En parallèle, lorsqu'un tiers est responsable — exploitant d'une structure sportive, organisateur d'un événement, propriétaire d'un bien défectueux — sa responsabilité peut être recherchée.",
    procedure: "La démarche consiste à analyser les contrats d'assurance de la victime afin d'activer les garanties applicables, à identifier les éventuelles responsabilités de tiers, et à négocier ou à faire juger l'indemnisation de l'ensemble des préjudices subis.",
  },
  {
    num: "04",
    title: "Accidents du travail",
    subtitle: "Code de la sécurité sociale · Articles L. 451-1 et suivants",
    tagline: "Faute inexcusable de l'employeur, maladies professionnelles.",
    body: "Le salarié victime d'un accident du travail ou d'une maladie professionnelle bénéficie d'une indemnisation forfaitaire versée par la Caisse Primaire d'Assurance Maladie (CPAM). Toutefois, lorsque l'accident ou la maladie résulte de la faute inexcusable de l'employeur, la victime peut obtenir une indemnisation complémentaire plus complète de ses préjudices.\n\nLa faute inexcusable est caractérisée lorsque l'employeur avait ou aurait dû avoir conscience du danger auquel était exposé le salarié et n'a pas pris les mesures nécessaires pour l'en préserver. Elle ouvre droit à la majoration des rentes et à la réparation des préjudices personnels non couverts par la législation professionnelle.",
    procedure: "La procédure se déroule devant le Pôle social du Tribunal judiciaire. Une phase de conciliation préalable est organisée. Il convient également d'assurer l'articulation entre l'indemnisation au titre de la législation professionnelle et les éventuels recours en responsabilité de droit commun contre des tiers impliqués dans la survenance du dommage.",
  },
  {
    num: "05",
    title: "Agressions & infractions pénales",
    subtitle: "Articles 706-3 et suivants du Code de procédure pénale",
    tagline: "Constitution de partie civile, CIVI, FGTI.",
    body: "Toute personne ayant subi un dommage corporel résultant d'une infraction pénale — agression physique, violence volontaire, viol, atteinte à l'intégrité — peut obtenir une indemnisation, y compris lorsque l'auteur est inconnu, insolvable ou non poursuivi.\n\nLa Commission d'Indemnisation des Victimes d'Infractions (CIVI) permet d'obtenir une indemnisation versée par le Fonds de Garantie des victimes d'actes de Terrorisme et d'autres Infractions (FGTI), indépendamment des suites pénales données à l'affaire. La constitution de partie civile permet quant à elle d'obtenir réparation dans le cadre de la procédure pénale elle-même.",
    procedure: "L'accompagnement porte sur l'ensemble de la procédure : dépôt de plainte, constitution de partie civile devant la juridiction répressive, saisine de la CIVI et du FGTI, suivi de l'expertise médicale et défense des intérêts de la victime à chaque étape — de l'instruction jusqu'à l'audience de jugement.",
  },
  {
    num: "06",
    title: "Militaires blessés",
    subtitle: "Code des pensions militaires d'invalidité",
    tagline: "Accompagnement spécialisé des militaires en service.",
    body: "Les militaires et gendarmes blessés en service — en opérations extérieures (OPEX) ou sur le territoire national — bénéficient d'un régime d'indemnisation spécifique, distinct du droit commun, articulé autour de trois dispositifs complémentaires.\n\nLa Pension Militaire d'Invalidité (PMI) indemnise forfaitairement le militaire blessé dès lors que la blessure est imputable au service et que les seuils de taux d'invalidité sont atteints. La jurisprudence Brugnot (Conseil d'État, 2005, complétée par l'arrêt Hamblin, 2013) ouvre droit à une indemnisation complémentaire des préjudices non couverts. Enfin, une réparation intégrale est possible lorsque le dommage résulte d'une faute de l'État.",
    procedure: "L'accompagnement porte sur la constitution du dossier de PMI, l'assistance lors des expertises médicales déterminant le taux d'invalidité, la contestation des décisions de la commission de réforme, et les recours contentieux devant le tribunal administratif en vue d'une indemnisation intégrale des préjudices.",
  },
]
